### ISSUE TITLE
The airplane model in the example is too bright and how to fix it?

### ISSUE THREAD

**Issue by ghoshaw** [svtek/ARKitEnvironmentMapper#7]
I install the example in iphone6s, but the model is too bright. 
![img_2077](https://user-images.githubusercontent.com/23494873/42319713-6326b2a6-8085-11e8-80f1-9faa31c50849.PNG)
I tried to change the code in ARKitEnvironmentMapper/Classes/ImageConverter.swift, such as  changing " let ev = (1 / 2) * (maxLightIntensity - estimatedIntensity) / maxLightIntensity" to "let ev = (1 / 200) * (maxLightIntensity - estimatedIntensity) / maxLightIntensity" and the variable "experimentalExposureCorrectionEnabled" in ARKitEnvironmentMapper+Options.swift changed to be true , but nothing changed, the model is still too bright. How should I fix this problem?

**Comment by halileohalilei** [comment]
Hi @ghoshaw, there is another open issue that describes the same problem. Can you have a look at that and see how he resolved it? Also, can you try fiddling with the ship.scn file in the project? It seems to me that the light source inside the scene is a bit too bright.

**Comment by ghoshaw** [comment]
Thanks !
